<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="DevMacro">
    <title>Jet Wash</title>
    <link rel="stylesheet" href="<?php echo DIRCSS."Lib/materialize.min.css";?>">
    <link rel="stylesheet" href="<?php echo DIRCSS."custom.css";?>">
    <script type="text/javascript" src="<?php echo DIRJS.'Lib/jquery-3.3.1.min.js';?>"></script>
    <script type="text/javascript" src="<?php echo DIRJS.'Lib/materialize.min.js';?>"></script>
    <?php use Src\Classes\Render;?>
</head>
<body>
    <header class="row blue">
        <div class="container">
            <?php echo Render::addHeader();?>
            <?php echo Render::addMenu();?>
        </div>
    </header>
    <div class="container">
        <main class="row">
            <div class="col s12 conteudo">
                <h2>Área de Conteudo Dinâmico</h2>
                <a id="teste2" class="btn left waves-effect waves-light modal-trigger" data-target="modal">Teste de Views</a>
            </div>
        </main>
    </div>
    <?php echo Render::addModal();?>
    <script type="text/javascript" src="<?php echo DIRJS.'Api/inicializarEventos.js';?>"></script>
    <script type="text/javascript" src="<?php echo DIRJS.'Api/cacheConfig.js';?>"></script>
    <script type="text/javascript" src="<?php echo DIRJS.'Api/carregarViews.js';?>"></script>
    <script type="text/javascript" src="<?php echo DIRJS.'Api/executarAcoes.js';?>"></script>
    <script type="text/javascript" src="<?php echo DIRJS.'Api/documentReady.js';?>"></script>
</body>
</html>
