<h3>Endereço</h3>
<form id="endereco" class="col s12">
    <div class="input-field col s12">
        <label for="cep">CEP</label>
        <input type="text" id="cep" name="cep" class="validate" required/>
        <span class="helper-text cep" data-error="informe seu cep para carregar o endereço" data-success="ok"></span>
    </div>
    <div class="input-field col s12"> 
        <label for="rua">Rua</label>
        <input type="text" id="rua" name="rua" class="validate" disabled required/>
        <span class="helper-text rua" data-error="rua inválido" data-success="ok"></span>
    </div>
    <div class="input-field col s12">
        <label for="numero">Número</label>
        <input type="number" id="numero" name="numero" class="validate" disabled required/>
        <span class="helper-text numero" data-error="numero inválido" data-success="ok"></span>
    </div>
    <div class="input-field col s12">
        <label for="bairro">Bairro</label>
        <input type="text" id="bairro" name="bairro" class="validate" disabled required/>
        <span class="helper-text bairro" data-error="bairro inválido" data-success="ok"></span>
    </div>
    <div class="input-field col s12">
        <label for="municipio">Município</label>
        <input type="text" id="municipio" name="municipio" class="validate" disabled required/>
        <span class="helper-text municipio" data-error="municipio inválido" data-success="ok"></span>
    </div>
    <div class="input-field col s12">
        <label for="uf">UF</label>
        <input type="text" id="uf" name="uf" class="validate" disabled required/>
        <span class="helper-text uf" data-error="uf inválido" data-success="ok"></span>
    </div>
    
    <a class="btn modal-close waves-effect waves-light modal-trigger cancelar">Cancelar</a>
    <input type="submit" class="btn right waves-effect waves-light" value="Avançar"/>
</form>