<h3>Perfil Cliente</h3>
<form id="perfilCliente" class="col s12">
    <div class="input-field col s12">
        <input type="text" id="nome" name="nome" class="validate" required/>
        <label for="pnome">Primeiro nome</label>
        <span class="helper-text nome" data-error="Digite seu nome" data-success="ok"></span>
    </div>
    <div class="input-field col s12">
        <label for="unome">Sobrenome</label>
        <input type="text" id="sobrenome" name="sobrenome" class="validate" required>
        <span class="helper-text sobrenome" data-error="Digite seu sobrenome" data-success="ok"></span>
    </div>
    <div class="input-field col s12">
        <label for="celular">Celular</label>
        <input type="number" id="celular" name="celular" class="validate" required>
        <span class="helper-text celular" data-error="Digite seu número de celular" data-success="ok"></span>
    </div>
    <a class="btn modal-close waves-effect waves-light modal-trigger cancelar">Cancelar</a>
    <input type="submit" class="btn right waves-effect waves-light" value="Finalizar"/>
</form>